package corpus

import (
	"fmt"
	"sort"
	"strings"
)

// Report aggregates []Result into the confusion matrix and headline rates.
type Report struct {
	Results []Result

	// Malicious (non-gap) counts.
	TruePositives  int
	FalseNegatives int
	// Malicious (KnownGap) counts.
	KnownGapMisses int
	BonusCatches   int
	// Benign counts.
	TrueNegatives         int
	FalsePositiveTripwire int
	FalsePositiveExfil    int
}

// Build aggregates raw results into a Report.
func Build(results []Result) Report {
	r := Report{Results: results}
	for _, res := range results {
		switch res.Outcome {
		case OutcomeTruePositive:
			r.TruePositives++
		case OutcomeFalseNegative:
			r.FalseNegatives++
		case OutcomeKnownGapMiss:
			r.KnownGapMisses++
		case OutcomeBonusCatch:
			r.BonusCatches++
		case OutcomeTrueNegative:
			r.TrueNegatives++
		case OutcomeFalsePositiveTripwire:
			r.FalsePositiveTripwire++
		case OutcomeFalsePositiveExfil:
			r.FalsePositiveExfil++
		}
	}
	return r
}

// MaliciousNonGapTotal is the denominator for the headline detection rate.
func (r Report) MaliciousNonGapTotal() int { return r.TruePositives + r.FalseNegatives }

// DetectionRate is EXFIL-tier proof achieved / non-gap malicious scenarios.
// Known-gap scenarios are excluded — see scenario.go for why.
func (r Report) DetectionRate() float64 {
	total := r.MaliciousNonGapTotal()
	if total == 0 {
		return 0
	}
	return float64(r.TruePositives) / float64(total)
}

// BenignTotal is the denominator for the false-positive rate.
func (r Report) BenignTotal() int {
	return r.TrueNegatives + r.FalsePositiveTripwire + r.FalsePositiveExfil
}

// FalsePositiveRate is the OPERATIONAL rate: any trip (SUSPICIOUS or EXFIL)
// on a benign scenario. In block mode a SUSPICIOUS trip blocks the call and
// in eBPF/sensor mode it kills the process — so this is the number that
// answers "does Interlock take enforcement action on legitimate traffic."
func (r Report) FalsePositiveRate() float64 {
	total := r.BenignTotal()
	if total == 0 {
		return 0
	}
	return float64(r.FalsePositiveTripwire+r.FalsePositiveExfil) / float64(total)
}

// FalsePositiveRateExfil is the severe-tier rate: EXFIL specifically
// (value-overlap proof) achieved on benign content. This should be ~0%;
// any nonzero value here is a real bug, not a documented design trade-off.
func (r Report) FalsePositiveRateExfil() float64 {
	total := r.BenignTotal()
	if total == 0 {
		return 0
	}
	return float64(r.FalsePositiveExfil) / float64(total)
}

type variantBreakdown struct {
	Variant                 Variant
	TP, FN, GapMiss, Bonus  int
	TN, FPTripwire, FPExfil int
}

func (r Report) byVariant() []variantBreakdown {
	m := map[Variant]*variantBreakdown{}
	order := []Variant{}
	for _, res := range r.Results {
		v := res.Scenario.Variant
		vb, ok := m[v]
		if !ok {
			vb = &variantBreakdown{Variant: v}
			m[v] = vb
			order = append(order, v)
		}
		switch res.Outcome {
		case OutcomeTruePositive:
			vb.TP++
		case OutcomeFalseNegative:
			vb.FN++
		case OutcomeKnownGapMiss:
			vb.GapMiss++
		case OutcomeBonusCatch:
			vb.Bonus++
		case OutcomeTrueNegative:
			vb.TN++
		case OutcomeFalsePositiveTripwire:
			vb.FPTripwire++
		case OutcomeFalsePositiveExfil:
			vb.FPExfil++
		}
	}
	sort.Slice(order, func(i, j int) bool { return order[i] < order[j] })
	out := make([]variantBreakdown, 0, len(order))
	for _, v := range order {
		out = append(out, *m[v])
	}
	return out
}

// Markdown renders the full published report matching docs/performance.md's style.
func (r Report) Markdown() string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Detection and False-Positive Rate — Benign/Malicious Corpus\n\n")
	fmt.Fprintf(&b, "Generated by `internal/corpus` (also exercised in `internal/corpus/corpus_test.go`, CI-safe — no root/BTF/kind required). Regenerate with `make fp-corpus`.\n\n")

	fmt.Fprintf(&b, "## What these numbers are and are not\n\n")
	fmt.Fprintf(&b, "Every scenario drives `internal/engine.Engine` directly — `IngestResult`/`EvaluateRequest` for the proxy (Variant A), `IngestSyscall` for eBPF (Variant B), `IngestSyscallSensor` for the v0.3 Phase 1 sensor-only mode. There is no MCP proxy, no kernel, no network in this corpus; eBPF allowlist filtering happens in `internal/ebpf/sensor.go` before an event ever reaches the engine, so a corpus \"non-allowlisted connect\" is exactly what the engine would see in production.\n\n")
	fmt.Fprintf(&b, "Two outcome dimensions are scored per scenario, and they answer different questions:\n\n")
	fmt.Fprintf(&b, "- **TrippedAny** — any step returned a non-empty verdict (`SUSPICIOUS` or `EXFIL`). After ROADMAP §1, only `EXFIL` hard-blocks/kills; `SUSPICIOUS` emits evidence with `allowed_monitor` / `detected_only`. TrippedAny still counts verdict presence (including soft SUSPICIOUS).\n")
	fmt.Fprintf(&b, "- **TrippedExfil** — a step specifically reached verdict `EXFIL`, meaning `CheckOverlap`/`CheckOverlapPayload` proved a tainted value appears in the sink args/payload.\n\n")
	fmt.Fprintf(&b, "**Detection rate** below is EXFIL-tier (excludes documented `KnownGap` scenarios from the denominator — a catalogued gap is not a regression). **False-positive rate** is any-trip on benign (including soft SUSPICIOUS), with the EXFIL-tier false-positive rate reported separately since it should be, and currently is, zero.\n\n")

	fmt.Fprintf(&b, "## Headline\n\n")
	fmt.Fprintf(&b, "| Metric | Value |\n|---|---|\n")
	fmt.Fprintf(&b, "| Corpus size | %d scenarios (%d malicious, %d benign) |\n", len(r.Results), r.maliciousTotal(), r.BenignTotal())
	fmt.Fprintf(&b, "| **Detection rate** (EXFIL-tier, non-gap malicious) | **%s** (%d/%d) |\n", pct(r.DetectionRate()), r.TruePositives, r.MaliciousNonGapTotal())
	fmt.Fprintf(&b, "| **False-positive rate** (any trip, benign) | **%s** (%d/%d) |\n", pct(r.FalsePositiveRate()), r.FalsePositiveTripwire+r.FalsePositiveExfil, r.BenignTotal())
	fmt.Fprintf(&b, "| False-positive rate (EXFIL-tier only, benign) | %s (%d/%d) |\n", pct(r.FalsePositiveRateExfil()), r.FalsePositiveExfil, r.BenignTotal())
	fmt.Fprintf(&b, "| Known-gap misses (expected, catalogued) | %d |\n", r.KnownGapMisses)
	fmt.Fprintf(&b, "| Bonus catches (gap unexpectedly closed) | %d |\n\n", r.BonusCatches)

	fmt.Fprintf(&b, "## Confusion matrix\n\n")
	fmt.Fprintf(&b, "| | Count |\n|---|---:|\n")
	fmt.Fprintf(&b, "| True positive (EXFIL proven, non-gap malicious) | %d |\n", r.TruePositives)
	fmt.Fprintf(&b, "| False negative (EXFIL missed, non-gap malicious) | %d |\n", r.FalseNegatives)
	fmt.Fprintf(&b, "| Known-gap miss (EXFIL missed, documented gap) | %d |\n", r.KnownGapMisses)
	fmt.Fprintf(&b, "| Bonus catch (EXFIL achieved, documented gap) | %d |\n", r.BonusCatches)
	fmt.Fprintf(&b, "| True negative (benign, no trip) | %d |\n", r.TrueNegatives)
	fmt.Fprintf(&b, "| False positive — tripwire (benign, SUSPICIOUS only) | %d |\n", r.FalsePositiveTripwire)
	fmt.Fprintf(&b, "| False positive — EXFIL (benign, severe) | %d |\n\n", r.FalsePositiveExfil)

	fmt.Fprintf(&b, "## Breakdown by detection plane\n\n")
	fmt.Fprintf(&b, "| Variant | TP | FN | GapMiss | Bonus | TN | FP (tripwire) | FP (EXFIL) |\n|---|---:|---:|---:|---:|---:|---:|---:|\n")
	for _, vb := range r.byVariant() {
		fmt.Fprintf(&b, "| `%s` | %d | %d | %d | %d | %d | %d | %d |\n",
			vb.Variant, vb.TP, vb.FN, vb.GapMiss, vb.Bonus, vb.TN, vb.FPTripwire, vb.FPExfil)
	}
	fmt.Fprintf(&b, "\n")

	fmt.Fprintf(&b, "## Known-gap misses (expected)\n\n")
	fmt.Fprintf(&b, "Each corresponds to a `*_KnownGap` unit test in `internal/engine` — the corpus pins that the gap still exists rather than silently tolerating it.\n\n")
	fmt.Fprintf(&b, "| Scenario | Gap |\n|---|---|\n")
	for _, res := range r.Results {
		if res.Outcome == OutcomeKnownGapMiss || res.Outcome == OutcomeBonusCatch {
			marker := ""
			if res.Outcome == OutcomeBonusCatch {
				marker = " — **BONUS CATCH, gap closed, promote this scenario out of KnownGap**"
			}
			fmt.Fprintf(&b, "| `%s` | %s%s |\n", res.Scenario.ID, res.Scenario.GapNote, marker)
		}
	}
	fmt.Fprintf(&b, "\n")

	fmt.Fprintf(&b, "## False positives (benign scenarios that tripped)\n\n")
	fmt.Fprintf(&b, "| Scenario | Tier | Why (design note) |\n|---|---|---|\n")
	for _, res := range r.Results {
		if res.Outcome == OutcomeFalsePositiveTripwire || res.Outcome == OutcomeFalsePositiveExfil {
			tier := "tripwire (SUSPICIOUS)"
			if res.Outcome == OutcomeFalsePositiveExfil {
				tier = "**EXFIL — unexpected, investigate**"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", res.Scenario.ID, tier, res.Scenario.DesignNote)
		}
	}
	fmt.Fprintf(&b, "\n")

	fmt.Fprintf(&b, "## Discussion — does this reshape the logic?\n\n")
	fmt.Fprintf(&b, "%s\n\n", r.discussion())

	fmt.Fprintf(&b, "## Reproduce\n\n```bash\ngo test ./internal/corpus/...\nmake fp-corpus   # regenerates this file\n```\n")

	return b.String()
}

func (r Report) maliciousTotal() int {
	return r.TruePositives + r.FalseNegatives + r.KnownGapMisses + r.BonusCatches
}

func (r Report) discussion() string {
	var b strings.Builder
	b.WriteString("**EXFIL-tier precision is high.** The false-positive rate at the EXFIL tier is " + pct(r.FalsePositiveRateExfil()) + " — value-overlap matching only fires when a tainted value's exact literal or one of its nine canonical encoded forms is actually present. No benign scenario in this corpus accidentally satisfies that bar, including ones deliberately constructed to look encoding-adjacent (base64 of unrelated data, masked previews, ticket-ID-only references).\n\n")
	b.WriteString("**ROADMAP §1 remediated the sticky-leg tripwire.** `untrusted_content_present` no longer lights on sensitive-source results; `SUSPICIOUS` requires AllLit plus byte-level content-bind between untrusted excerpts and the sink; hard block/kill is reserved for `EXFIL`. Former ExpectTripByDesign sticky-leg scenarios are now true negatives. Remaining any-trip rows (if any) are intentional soft-SUSPICIOUS pins (`allowed_monitor` / `detected_only`), not hard-enforcement false positives.\n\n")
	fmt.Fprintf(&b, "**Leg decay** (`trifecta.leg_ttl` / `decay_after_calls`) dims sticky legs after idle time or N subsequent events so a poisoned session does not forever treat every sink as suspicious. Tainted values are retained so a late sink that still carries a secret can still reach EXFIL. The corpus exercises both dimensions (`benign_proxy_a_leg_decay_then_sink`, `benign_proxy_a_high_throughput_50_then_sink`, TTL past-boundary `benign_proxy_a_leg_ttl_decay_then_sink` at 31m, and still-lit under-boundary `benign_proxy_a_leg_ttl_still_lit_under_boundary` at 29m59s via `StepAdvanceTime`).\n\n")
	b.WriteString("**Extraction boundary.** `extractResultText` prefers MCP `content[].text`, then walks other JSON string leaves (bounded). Benign nested-metadata scenarios keep an unrelated sink so registered metadata taint does not EXFIL without overlap; the paired malicious scenario (`malicious_proxy_a_secret_outside_content_text`) proves buried secrets are tainted. Soft-SUSPICIOUS any-trip pins (natural product quotes, multi-server B→C binds) are intentional `allowed_monitor` noise for fetch-heavy agents — tune `content_bind_min_len` rather than hard-blocking.")
	return b.String()
}

func pct(f float64) string {
	return fmt.Sprintf("%.1f%%", f*100)
}
