// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	connectMapCgroupFilter                       = "cgroup_filter"
	connectMapCriticalDropCount                  = "critical_drop_count"
	connectMapCriticalEvents                     = "critical_events"
	connectMapDropCount                          = "drop_count"
	connectMapEvents                             = "events"
	connectMapLsmBlocklistCgroup                 = "lsm_blocklist_cgroup"
	connectMapLsmBlocklistPid                    = "lsm_blocklist_pid"
	connectMapPayloadCap                         = "payload_cap"
	connectMapPidFilter                          = "pid_filter"
	connectProgLsmSocketConnect                  = "lsm_socket_connect"
	connectProgTracepointSyscallsSysEnterConnect = "tracepoint__syscalls__sys_enter_connect"
	connectProgTracepointSyscallsSysEnterOpenat  = "tracepoint__syscalls__sys_enter_openat"
	connectProgTracepointSyscallsSysEnterSendmsg = "tracepoint__syscalls__sys_enter_sendmsg"
	connectProgTracepointSyscallsSysEnterSendto  = "tracepoint__syscalls__sys_enter_sendto"
	connectProgTracepointSyscallsSysEnterWrite   = "tracepoint__syscalls__sys_enter_write"
	connectProgTracepointSyscallsSysEnterWritev  = "tracepoint__syscalls__sys_enter_writev"
)

// loadConnect returns the embedded CollectionSpec for connect.
func loadConnect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load connect: %w", err)
	}

	return spec, err
}

// loadConnectObjects loads connect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*connectObjects
//	*connectPrograms
//	*connectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConnectObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadConnect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// connectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectSpecs struct {
	connectProgramSpecs
	connectMapSpecs
	connectVariableSpecs
}

// connectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectProgramSpecs struct {
	LsmSocketConnect                  *ebpf.ProgramSpec `ebpf:"lsm_socket_connect"`
	TracepointSyscallsSysEnterConnect *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_connect"`
	TracepointSyscallsSysEnterOpenat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterSendmsg *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_sendmsg"`
	TracepointSyscallsSysEnterSendto  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
	TracepointSyscallsSysEnterWrite   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_write"`
	TracepointSyscallsSysEnterWritev  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_writev"`
}

// connectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectMapSpecs struct {
	CgroupFilter       *ebpf.MapSpec `ebpf:"cgroup_filter"`
	CriticalDropCount  *ebpf.MapSpec `ebpf:"critical_drop_count"`
	CriticalEvents     *ebpf.MapSpec `ebpf:"critical_events"`
	DropCount          *ebpf.MapSpec `ebpf:"drop_count"`
	Events             *ebpf.MapSpec `ebpf:"events"`
	LsmBlocklistCgroup *ebpf.MapSpec `ebpf:"lsm_blocklist_cgroup"`
	LsmBlocklistPid    *ebpf.MapSpec `ebpf:"lsm_blocklist_pid"`
	PayloadCap         *ebpf.MapSpec `ebpf:"payload_cap"`
	PidFilter          *ebpf.MapSpec `ebpf:"pid_filter"`
}

// connectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectVariableSpecs struct {
}

// connectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectObjects struct {
	connectPrograms
	connectMaps
	connectVariables
}

func (o *connectObjects) Close() error {
	return _ConnectClose(
		&o.connectPrograms,
		&o.connectMaps,
	)
}

// connectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectMaps struct {
	CgroupFilter       *ebpf.Map `ebpf:"cgroup_filter"`
	CriticalDropCount  *ebpf.Map `ebpf:"critical_drop_count"`
	CriticalEvents     *ebpf.Map `ebpf:"critical_events"`
	DropCount          *ebpf.Map `ebpf:"drop_count"`
	Events             *ebpf.Map `ebpf:"events"`
	LsmBlocklistCgroup *ebpf.Map `ebpf:"lsm_blocklist_cgroup"`
	LsmBlocklistPid    *ebpf.Map `ebpf:"lsm_blocklist_pid"`
	PayloadCap         *ebpf.Map `ebpf:"payload_cap"`
	PidFilter          *ebpf.Map `ebpf:"pid_filter"`
}

func (m *connectMaps) Close() error {
	return _ConnectClose(
		m.CgroupFilter,
		m.CriticalDropCount,
		m.CriticalEvents,
		m.DropCount,
		m.Events,
		m.LsmBlocklistCgroup,
		m.LsmBlocklistPid,
		m.PayloadCap,
		m.PidFilter,
	)
}

// connectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectVariables struct {
}

// connectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectPrograms struct {
	LsmSocketConnect                  *ebpf.Program `ebpf:"lsm_socket_connect"`
	TracepointSyscallsSysEnterConnect *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_connect"`
	TracepointSyscallsSysEnterOpenat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterSendmsg *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_sendmsg"`
	TracepointSyscallsSysEnterSendto  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
	TracepointSyscallsSysEnterWrite   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_write"`
	TracepointSyscallsSysEnterWritev  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_writev"`
}

func (p *connectPrograms) Close() error {
	return _ConnectClose(
		p.LsmSocketConnect,
		p.TracepointSyscallsSysEnterConnect,
		p.TracepointSyscallsSysEnterOpenat,
		p.TracepointSyscallsSysEnterSendmsg,
		p.TracepointSyscallsSysEnterSendto,
		p.TracepointSyscallsSysEnterWrite,
		p.TracepointSyscallsSysEnterWritev,
	)
}

func _ConnectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connect_x86_bpfel.o
var _ConnectBytes []byte
